apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    {{- include "selectorLabels" . | nindent 6 }}
